version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    assignees:
      - "justedlev"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
