name: Sonatype Workflow

on:
  release:
    types: [ published ]
    tags: [ "v*.*.*" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Set up JDK 11
        id: jdk
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Setup Maven settings.xml
        id: maven-settings
        uses: whelk-io/maven-settings-xml-action@v11
        with:
          profiles: |
            '[
              {
                "id": "gpg",
                "activations": {
                  "activeByDefault": false
                },
                "properties": {
                  "gpg.executable": "gpg",
                  "gpg.passphrase": "${secrets.MAVEN_GPG_PASSPHRASE}",
                  "gpg.keyname": "${secrets.GPG_KEYNAME}"
                }
              }
            ]'
          servers: |
            '[
              {
                "id": "central",
                "username": "${secrets.SONATYPE_USERNAME}",
                "password": "${secrets.SONATYPE_PASSWORD}"
              }
            ]'
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Publish to Sonatype Central
        run: mvn clean deploy -s $GITHUB_WORKSPACE/settings.xml -P gpg,release
